### ISSUE TITLE
Can't start vbar

### ISSUE THREAD

**Issue by Cakedy** [AndrewVos/vbar#13]
vbar start
```
/bin/bash: /home/cakedy/.config/vbar/vbarrc: Permission denied
2018/04/28 16:19:07 exit status 126
panic: exit status 126

goroutine 6 [running]:
log.Panic(0xc42017afb8, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:326 +0xc0
main.launch.func1(0xc420068ee0)
        /home/cakedy/go/src/github.com/AndrewVos/vbar/main.go:104 +0x89
created by main.launch
        /home/cakedy/go/src/github.com/AndrewVos/vbar/main.go:101 +0x10e
```

Default config file (the one from the examples folder).

OS: Gentoo Linux 4.15.18
Installed via go get.

**Comment by Makefile-dot-in** [comment]
Are the permissions for /home/cakedy/.config set so that you have read access?

**Comment by AndrewVos** [comment]
You should also make it executable:

    chmod +x ~/.config/chat/vbarrc

**Comment by Cakedy** [comment]
Making it executable made it work! Thanks!
